# read only data for a run modifier, either a difficulty setting or custom modifiers
extends SerializableData
class_name RunModifierData

@export var run_modifier_name: String = "Modifier 1"
@export var run_modifier_description: String = "Description of Modifier"
@export var run_modifier_is_custom: bool = false	# whether this should appear as a custom modifier
@export var run_modifier_exclusive_to_modifier_ids: Array[String] = []	# ids of modifiers that are exclusive to this one (unchecks them on selecting this one). Only useful for custom modifiers

@export var run_modifier_modifier_script_path: String = ""	# path to BaseRunModifier script
@export var run_modifier_interceptor_script_paths: Array[String] = []	# interceptors generated by the modifier on run start
