# tooltip displaying info on a single keyword
# generated by KeywordContainer
extends PanelContainer

@onready var rich_text_label = $RichTextLabel

func init(keyword_object_id: String) -> void:
	var keyword_data: KeywordData = Global.get_keyword_data(keyword_object_id)
	if keyword_data == null:
		push_error("No keyword of id ", keyword_object_id, " found")
	else:
		rich_text_label.parse_bbcode(keyword_data.keyword_text_bb_code)
