## Abstract class for any action that needs to perform an action against a set of cards.
## Extend and override perform_action() to provide functionality to the cards.
extends BaseAction
class_name BaseCardsetAction

### Override

func perform_action() -> void:
	# picked_cards = get_picked_cards()
	# iterate over and perform actions against picked_cards
	breakpoint

### Keep

## Gets the cards to use for the cardset action. This can come from a variety of sources.
## Typically generated by an ActionPickCards and can reference the picked_cards from that.
## May also be directly generated and passed in a picked_cards parameter,
## or use the card that invoked it with pick_played_card parameter 
func _get_picked_cards() -> Array[CardData]:
	# if pick_played_card, use the card that invoked the action as the cardset
	var pick_played_card: bool = get_action_value("pick_played_card", false)
	if pick_played_card:
		if card_play_request == null:
			push_error("No CardPlayRequest found")
			return []
		elif card_play_request.card_data == null:
			push_error("No card found in CardPlayRequest")
			return []
		else:
			# picks currently played card
			var picked_cards: Array[CardData] = []
			picked_cards.append(card_play_request.card_data)
			return picked_cards
	
	# derives the cards to use from the parent action if possible
	if parent_action != null:
		if parent_action is ActionBasePickCards:
			return parent_action.picked_cards
	else:
		# fall back to picked_cards value
		var picked_cards: Array = get_action_value("picked_cards", [])
		# convert typed array
		var returned_cards: Array[CardData] = []
		for card_data in picked_cards:
			returned_cards.append(card_data)
		
		return returned_cards
		
	
	return []

func _to_string():
	return "BaseCardset Action"
