import json

with open(r"C:\Users\zuolei01\Documents\MyGame\src\data\traits.json", encoding="utf-8") as f:
    traits = json.load(f)

with open(r"C:\Users\zuolei01\Documents\MyGame\src\data\reactions.json", encoding="utf-8") as f:
    reactions = json.load(f)

# Build trait lookup
trait_by_id = {t["id"]: t for t in traits}

# --- test_trait_matrix.gd ---
lines = []
lines.append('## GdUnit4 test suite for ISSUE-021: Trait coverage matrix.')
lines.append('## Parameterized over all 80 trait ids — one test function per trait.')
lines.append('## TODO: Add en locale .po file in a future ticket (zh-CN flavor only for now).')
lines.append('extends GdUnitTestSuite')
lines.append('')
lines.append('const TraitScript      := preload("res://data/trait.gd")')
lines.append('const SlotScript       := preload("res://data/slot.gd")')
lines.append('const CardScript       := preload("res://data/card.gd")')
lines.append('const LoaderScript     := preload("res://data/loader.gd")')
lines.append('const BattleStateScript := preload("res://core/battle_state.gd")')
lines.append('const EmitScript       := preload("res://core/emit.gd")')
lines.append('')
lines.append('const TRAITS_PATH := "res://data/traits.json"')
lines.append('')
lines.append('')
lines.append('func _read_file(path: String) -> String:')
lines.append('\tvar f := FileAccess.open(path, FileAccess.READ)')
lines.append('\tassert_that(f).is_not_null()')
lines.append('\tvar text := f.get_as_text()')
lines.append('\tf.close()')
lines.append('\treturn text')
lines.append('')
lines.append('')
lines.append('func _load_traits_by_id() -> Dictionary:')
lines.append('\tvar loader = LoaderScript.new()')
lines.append('\tvar arr: Array = loader.load_traits_from_json(_read_file(TRAITS_PATH))')
lines.append('\tvar d: Dictionary = {}')
lines.append('\tfor t in arr:')
lines.append('\t\td[t.id] = t')
lines.append('\treturn d')
lines.append('')
lines.append('')
lines.append('## Build a card with one trait in slot 0.')
lines.append('func _make_card_single(t: Resource) -> Resource:')
lines.append('\tvar s0 = SlotScript.new()')
lines.append('\ts0.index = 0')
lines.append('\ts0.trait_ref = t')
lines.append('\ts0.locked = true')
lines.append('\ts0.post_load()')
lines.append('\tvar s1 = SlotScript.new()')
lines.append('\ts1.index = 1')
lines.append('\ts1.locked = false')
lines.append('\ts1.post_load()')
lines.append('\tvar s2 = SlotScript.new()')
lines.append('\ts2.index = 2')
lines.append('\ts2.locked = false')
lines.append('\ts2.post_load()')
lines.append('\tvar card = CardScript.new()')
lines.append('\tcard.slots = [s0, s1, s2]')
lines.append('\treturn card')
lines.append('')
lines.append('')
lines.append('## Build a card: slot0=OnPlay stub, slot1=OnTraitFired trait.')
lines.append('## Used for traits that trigger on OnTraitFired (trigger==7).')
lines.append('func _make_card_otf(onplay_stub: Resource, otf_trait: Resource) -> Resource:')
lines.append('\tvar s0 = SlotScript.new()')
lines.append('\ts0.index = 0')
lines.append('\ts0.trait_ref = onplay_stub')
lines.append('\ts0.locked = true')
lines.append('\ts0.post_load()')
lines.append('\tvar s1 = SlotScript.new()')
lines.append('\ts1.index = 1')
lines.append('\ts1.trait_ref = otf_trait')
lines.append('\ts1.locked = false')
lines.append('\ts1.post_load()')
lines.append('\tvar s2 = SlotScript.new()')
lines.append('\ts2.index = 2')
lines.append('\ts2.locked = false')
lines.append('\ts2.post_load()')
lines.append('\tvar card = CardScript.new()')
lines.append('\tcard.slots = [s0, s1, s2]')
lines.append('\treturn card')
lines.append('')
lines.append('')
lines.append('func _make_stub_onplay(stub_id: String) -> Resource:')
lines.append('\tvar t = TraitScript.new()')
lines.append('\tt.id = stub_id')
lines.append('\tt.trigger = 0  # OnPlay')
lines.append('\tt.effect_type = "Damage"')
lines.append('\tt.effect_value = 1')
lines.append('\tt.cooldown_per_turn = -1')
lines.append('\tt.axis_timing = 0')
lines.append('\tt.axis_scope = 0')
lines.append('\tt.axis_school = 0')
lines.append('\tt.rarity = 0')
lines.append('\tt.removable = true')
lines.append('\tt.flavor = ""')
lines.append('\treturn t')
lines.append('')
lines.append('')

# Generate one test per trait
trigger_map = {
    "OnPlay": 0, "OnDraw": 1, "OnDiscard": 2, "OnKill": 3,
    "OnHit": 4, "StartTurn": 5, "EndTurn": 6, "OnTraitFired": 7
}

for t in traits:
    tid = t["id"]
    trigger = t["trigger"]
    effect_type = t["effect_type"]
    effect_value = t["effect_value"]
    trigger_int = trigger_map[trigger]

    func_name = "test_trait_" + tid
    lines.append(f'func {func_name}() -> void:')
    lines.append(f'\tvar by_id := _load_traits_by_id()')
    lines.append(f'\tvar trait_res: Resource = by_id["{tid}"]')
    lines.append(f'\tassert_that(trait_res).is_not_null()')

    if trigger == "OnTraitFired":
        # Need to fire OnPlay first to get OnTraitFired bubble
        lines.append(f'\t# OnTraitFired trait: use OTF helper card to fire via OnPlay bubble')
        lines.append(f'\tvar stub := _make_stub_onplay("_stub_for_{tid}")')
        lines.append(f'\tvar card := _make_card_otf(stub, trait_res)')
        lines.append(f'\tvar state := BattleStateScript.new()')
        lines.append(f'\tvar emitter := EmitScript.new()')
        lines.append(f'\temitter.emit(state, 0, card)  # OnPlay fires stub -> bubbles OnTraitFired')
        lines.append(f'\t# Find the log entry for this trait')
        lines.append(f'\tvar found := false')
        lines.append(f'\tfor entry in state.trait_fire_log:')
        lines.append(f'\t\tif entry["source_trait_id"] == "{tid}":')
        lines.append(f'\t\t\tassert_str(entry["effect_type"]).is_equal("{effect_type}")')
        lines.append(f'\t\t\tassert_int(entry["effect_value"]).is_equal({effect_value})')
        lines.append(f'\t\t\tfound = true')
        lines.append(f'\t\t\tbreak')
        lines.append(f'\tassert_bool(found).is_true()')
    else:
        lines.append(f'\tvar card := _make_card_single(trait_res)')
        lines.append(f'\tvar state := BattleStateScript.new()')
        lines.append(f'\tvar emitter := EmitScript.new()')
        lines.append(f'\temitter.emit(state, {trigger_int}, card)  # {trigger}')
        lines.append(f'\tassert_int(state.trait_fire_log.size()).is_greater_equal(1)')
        lines.append(f'\tvar entry := state.trait_fire_log[0]')
        lines.append(f'\tassert_str(entry["source_trait_id"]).is_equal("{tid}")')
        lines.append(f'\tassert_str(entry["effect_type"]).is_equal("{effect_type}")')
        lines.append(f'\tassert_int(entry["effect_value"]).is_equal({effect_value})')
    lines.append('')

output = "\n".join(lines)
with open(r"C:\Users\zuolei01\Documents\MyGame\src\tests\test_trait_matrix.gd", "w", encoding="utf-8") as f:
    f.write(output)

print(f"Written test_trait_matrix.gd with {len(traits)} test functions")

# --- test_reaction_matrix.gd ---
lines2 = []
lines2.append('## GdUnit4 test suite for ISSUE-021: Reaction coverage matrix.')
lines2.append('## Parameterized over all 25 reaction ids — one test function per reaction.')
lines2.append('## TODO: Add en locale .po file in a future ticket (zh-CN flavor only for now).')
lines2.append('extends GdUnitTestSuite')
lines2.append('')
lines2.append('const TraitScript          := preload("res://data/trait.gd")')
lines2.append('const SlotScript           := preload("res://data/slot.gd")')
lines2.append('const CardScript           := preload("res://data/card.gd")')
lines2.append('const ReactionScript       := preload("res://data/reaction.gd")')
lines2.append('const LoaderScript         := preload("res://data/loader.gd")')
lines2.append('const BattleStateScript    := preload("res://core/battle_state.gd")')
lines2.append('const EmitScript           := preload("res://core/emit.gd")')
lines2.append('')
lines2.append('const TRAITS_PATH    := "res://data/traits.json"')
lines2.append('const REACTIONS_PATH := "res://data/reactions.json"')
lines2.append('')
lines2.append('')
lines2.append('func _read_file(path: String) -> String:')
lines2.append('\tvar f := FileAccess.open(path, FileAccess.READ)')
lines2.append('\tassert_that(f).is_not_null()')
lines2.append('\tvar text := f.get_as_text()')
lines2.append('\tf.close()')
lines2.append('\treturn text')
lines2.append('')
lines2.append('')
lines2.append('func _load_traits_by_id() -> Dictionary:')
lines2.append('\tvar loader = LoaderScript.new()')
lines2.append('\tvar arr: Array = loader.load_traits_from_json(_read_file(TRAITS_PATH))')
lines2.append('\tvar d: Dictionary = {}')
lines2.append('\tfor t in arr:')
lines2.append('\t\td[t.id] = t')
lines2.append('\treturn d')
lines2.append('')
lines2.append('')
lines2.append('func _load_reactions_by_id() -> Dictionary:')
lines2.append('\tvar loader = LoaderScript.new()')
lines2.append('\tvar arr: Array = loader.load_reactions_from_json(_read_file(REACTIONS_PATH))')
lines2.append('\tvar d: Dictionary = {}')
lines2.append('\tfor r in arr:')
lines2.append('\t\td[r.id] = r')
lines2.append('\treturn d')
lines2.append('')
lines2.append('')
lines2.append('## Build a card with two traits, one in slot 0, one in slot 1.')
lines2.append('func _make_card2(t0: Resource, t1: Resource) -> Resource:')
lines2.append('\tvar s0 = SlotScript.new()')
lines2.append('\ts0.index = 0')
lines2.append('\ts0.trait_ref = t0')
lines2.append('\ts0.locked = true')
lines2.append('\ts0.post_load()')
lines2.append('\tvar s1 = SlotScript.new()')
lines2.append('\ts1.index = 1')
lines2.append('\ts1.trait_ref = t1')
lines2.append('\ts1.locked = false')
lines2.append('\ts1.post_load()')
lines2.append('\tvar s2 = SlotScript.new()')
lines2.append('\ts2.index = 2')
lines2.append('\ts2.locked = false')
lines2.append('\ts2.post_load()')
lines2.append('\tvar card = CardScript.new()')
lines2.append('\tcard.slots = [s0, s1, s2]')
lines2.append('\treturn card')
lines2.append('')
lines2.append('')
lines2.append('## Build a minimal Trait resource with given id and trigger int.')
lines2.append('func _make_trait_stub(tid: String, trigger_int: int, effect_type: String, effect_value: int) -> Resource:')
lines2.append('\tvar t = TraitScript.new()')
lines2.append('\tt.id = tid')
lines2.append('\tt.trigger = trigger_int')
lines2.append('\tt.effect_type = effect_type')
lines2.append('\tt.effect_value = effect_value')
lines2.append('\tt.cooldown_per_turn = -1 if trigger_int != 3 and trigger_int != 7 else 1')
lines2.append('\tt.axis_timing = trigger_int')
lines2.append('\tt.axis_scope = 0')
lines2.append('\tt.axis_school = 0')
lines2.append('\tt.rarity = 0')
lines2.append('\tt.removable = true')
lines2.append('\tt.flavor = ""')
lines2.append('\treturn t')
lines2.append('')
lines2.append('')

# Generate one test per reaction
for r in reactions:
    rid = r["id"]
    wf0 = r["watch_for"][0]
    wf1 = r["watch_for"][1]
    timing_str = r["timing"]
    timing_int = trigger_map[timing_str]
    override = r["override_effect"]

    t0 = trait_by_id.get(wf0)
    t1 = trait_by_id.get(wf1)

    t0_trigger_int = trigger_map[t0["trigger"]] if t0 else timing_int
    t1_trigger_int = trigger_map[t1["trigger"]] if t1 else timing_int
    t0_effect = t0["effect_type"] if t0 else "Damage"
    t0_value = t0["effect_value"] if t0 else 1
    t1_effect = t1["effect_type"] if t1 else "Damage"
    t1_value = t1["effect_value"] if t1 else 1

    func_name = "test_reaction_" + rid
    lines2.append(f'func {func_name}() -> void:')
    lines2.append(f'\tvar by_id := _load_traits_by_id()')
    lines2.append(f'\tvar rx_by_id := _load_reactions_by_id()')
    lines2.append(f'\t# Load the reaction')
    lines2.append(f'\tvar reaction: Resource = rx_by_id["{rid}"]')
    lines2.append(f'\tassert_that(reaction).is_not_null()')
    lines2.append(f'\t# Build stubs for watch_for traits at the reaction timing so the reaction fires')
    lines2.append(f'\tvar t0_res: Resource')
    lines2.append(f'\tvar t1_res: Resource')
    lines2.append(f'\tif by_id.has("{wf0}"):')
    lines2.append(f'\t\tt0_res = by_id["{wf0}"]')
    lines2.append(f'\telse:')
    lines2.append(f'\t\tt0_res = _make_trait_stub("{wf0}", {timing_int}, "{t0_effect}", {t0_value})')
    lines2.append(f'\tif by_id.has("{wf1}"):')
    lines2.append(f'\t\tt1_res = by_id["{wf1}"]')
    lines2.append(f'\telse:')
    lines2.append(f'\t\tt1_res = _make_trait_stub("{wf1}", {timing_int}, "{t1_effect}", {t1_value})')
    lines2.append(f'\t# Card has both watch_for traits')
    lines2.append(f'\tvar card := _make_card2(t0_res, t1_res)')
    lines2.append(f'\tvar state := BattleStateScript.new()')
    lines2.append(f'\tstate.reactions = [reaction]')
    lines2.append(f'\tvar emitter := EmitScript.new()')
    lines2.append(f'\temitter.emit(state, {timing_int}, card)  # {timing_str}')
    lines2.append(f'\t# Reaction fires and returns early — exactly 1 log entry')
    lines2.append(f'\tassert_int(state.trait_fire_log.size()).is_equal(1)')
    lines2.append(f'\tvar entry := state.trait_fire_log[0]')
    lines2.append(f'\tassert_str(entry["source"]).is_equal("reaction")')
    lines2.append(f'\tassert_str(entry["effect_type"]).is_equal("{override}")')
    lines2.append(f'\t# Parent trait default effects were NOT logged (no source=="trait" entries)')
    lines2.append(f'\tfor e in state.trait_fire_log:')
    lines2.append(f'\t\tassert_str(e["source"]).is_not_equal("trait")')
    lines2.append('')

output2 = "\n".join(lines2)
with open(r"C:\Users\zuolei01\Documents\MyGame\src\tests\test_reaction_matrix.gd", "w", encoding="utf-8") as f:
    f.write(output2)

print(f"Written test_reaction_matrix.gd with {len(reactions)} test functions")
